name: Build Book PDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create service account file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccountKey.json

      - name: Build HTML
        run: node generate-html.js

      - name: List files after HTML build
        run: ls -la

      - name: Generate PDF
        run: node generate-pdf.js

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Kirja_PDF
          path: Kirja_A5_PRINT.pdf
