name: feedback-proxy

on:
  repository_dispatch:
    types: [feedback]

jobs:
  send_feedback:
    runs-on: ubuntu-latest

    steps:
    - name: Send feedback to GitHub Issues
      run: |
        echo "BODY: $BODY"
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.COMMENT_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d "{\"title\": \"Kappalepalaute\", \"body\": \"$BODY\"}"
      env:
        BODY: ${{ github.event.client_payload.body }}
